theme: jekyll-theme-cayman
show_downloads: true
github:
  zip_url: https://github.com/g4b0-88/sqlserver-table-tree/archive/1.0.zip
  tar_url: https://github.com/g4b0-88/sqlserver-table-tree/archive/1.0.tar.gz
